import type { ClientState } from '../../../shared/protocol';

export function emptyClientState(): ClientState {
  return {
    agents: [],
    agentModes: [],
    toolPolicies: [],
    approvalPolicies: [],
    systemPrompts: [],
    modelProfiles: [],
    agentModeLinks: [],
    modeToolPolicyLinks: [],
    modeApprovalPolicyLinks: [],
    modeSystemPromptLinks: [],
    modeModelProfileLinks: [],
    conversations: [],
    conversationReuseLinks: [],
    conversationBranchLinks: [],
    agentConversationLinks: [],
    messages: [],
    messageRevisions: [],
    messageCurrentRevisionLinks: [],
    toolCalls: [],
    toolCallEvents: [],
    agentRuns: [],
    agentRunSourceLinks: [],
    agentRunTargetLinks: [],
    messageRunLinks: [],
    toolCallRunLinks: [],
    runConversationPolicies: [],
    runContextPolicies: [],
    runDeliveryPolicies: [],
    runEditPolicies: [],
    runModeLinks: [],
    runSystemPromptLinks: [],
    runModelProfileLinks: [],
    runToolPolicyLinks: [],
    runApprovalPolicyLinks: [],
    runConversationPolicyLinks: [],
    runContextPolicyLinks: [],
    runDeliveryPolicyLinks: [],
    runEditPolicyLinks: [],
    agentRunInputRevisions: []
  };
}
